### ISSUE TITLE
Better engine / propeller

### ISSUE THREAD

**Issue by magnetic-eagle** [SP-NTX/PZL-Koliber-family#1]
Hey @SP-NTX, if you give me a link to the POH of this aircraft, I can make you a custom propeller and engine ! :) AFAICS you got the default AeroMatic engine and prop, right ?

**Comment by SP-NTX** [comment]
well, the engine and propeller are really good at all, yes, they are by aeromatic but i edited them a lot. also, use only jsbsim-dev branch

**Comment by SP-NTX** [comment]
only propeller may be a bit not good

**Comment by magnetic-eagle** [comment]
Well, just let me know if you need help with anything - the splash image already looks promising (especially the gear seems to have a high level of detail !), so keep up the good work ! :)

**Comment by magnetic-eagle** [comment]
I was just looking at the nasal files you got … you are really cluttering the property tree, which is not good … also you use a lot of settimer loops which are officially discouraged in the wiki - would you mind me doing a bit of cleanup and send you a pull request ? 😃 
As for the "incidence" mentioned in auto-slats.nas, if you mean the angle of attack, you can find that in `/orientation/alpha-deg` ! :)

**Comment by SP-NTX** [comment]
well, we will have to do it... It's not ours aircraft, and the original is old one, its more than 5 years old

**Comment by SP-NTX** [comment]
auto slats are very complex thing in it. on ground they are not doing anything, after take off they are moving (based on speed), after landing... they have to be retracted manually ( i mean, by hand)

**Comment by SP-NTX** [comment]
If you want, you can do cleanup, but i will also do some cleanups in XML, and my friend is doing cleanup in folders and some files so...

**Comment by magnetic-eagle** [comment]
> well, we will have to do it... It's not ours aircraft, and the original is old one, its more than 5 years old

Ahhh, okay, thanks, that explains a lot indeed ! :)

**Comment by SP-NTX** [comment]
you can do, i have to manually edit ac3d file to make smooth shading work at all now

**Comment by magnetic-eagle** [comment]
Uh, what's your 3D software ? blender ?

**Comment by SP-NTX** [comment]
yes, but original author did something wrong with the model i think, after i've done new gears and added smooth shading, they work also in FG, but the aircraft model is smooth only in blender

**Comment by magnetic-eagle** [comment]
> i will also do some cleanups in XML, and my friend is doing cleanup in folders and some files so...

The more people the better ! :) Does your friend have a Github account ?

**Comment by magnetic-eagle** [comment]
> but the aircraft model is smooth only in blender

I'll take a look ! :) Can you add the Blender file to the repo, please ?

**Comment by SP-NTX** [comment]
will do

**Comment by SP-NTX** [comment]
done

**Comment by jakkos98** [comment]
Hello, 
@TheFGFSEagle I'm currently trying to make propeller for this aircraft, based on you're sugestions from this topic [New Aircraft - Promecc_Freccia](https://forum.flightgear.org/viewtopic.php?f=4&t=39659&start=75#p404939). 
Prop name: Sensenich 74dm6-0-58 designed fo 125-165 hp engines with speed range 120-170MPH
Diameter is: 78 inches
Pitch: 17.52 deg at 75% radius

Engine: 160hp, max RPM 2700
Cruise speed at 75% power altitude 0ft: 117 mph TAS
RPM at this condition 2470

This is my input and results in Java Prop:
![image](https://user-images.githubusercontent.com/40403643/190703335-8370c3c6-35f5-4668-bf7f-8f678ac796d7.png)
![image](https://user-images.githubusercontent.com/40403643/190703357-bbd8e2f6-e422-40e0-bc94-39e3856a7eff.png)
![image](https://user-images.githubusercontent.com/40403643/190703372-453a90a3-fe8c-41f7-a82e-2f2f0effe99d.png)
![image](https://user-images.githubusercontent.com/40403643/190703400-672d1d73-a129-40c6-816a-938a79345253.png)
![image](https://user-images.githubusercontent.com/40403643/190703434-816048d6-72ba-4918-9ffc-5651af19808c.png)

**Comment by SP-NTX** [comment]
@TheFGFSEagle  if you want it will be easier to communicate if you will join our discord server https://discord.gg/BxataJbS

**Comment by jakkos98** [comment]
I send wrong screens.
Will send correct in few minutes.

**Comment by magnetic-eagle** [comment]
> @TheFGFSEagle if you want it will be easier to communicate if you will join our discord server https://discord.gg/BxataJbS

Great, will join right now ! :)

@jakkos98 what you sent so far looks alright ! :)
