### ISSUE TITLE
Weak Engine

### ISSUE THREAD

**Issue by sryu1** [SP-NTX/PZL-Koliber-family#13]
I'm not sure why, but everytime I fly the aircraft, it barely exceeds 60 kts... Am I doing something wrong?

**Comment by SP-NTX** [comment]
Engine is in progress, just like FDM and systems and 3D, Make sure you are using jsbsim-dev branch with latest commit. For latest progress you can join our Discord server https://discord.gg/beADn2sWM6

**Comment by magnetic-eagle** [comment]
Yep, it had set the power too low until yesterday - so please, update your local copy of this repo, and as SP-NTX said, make sure you have the jsbsim-dev branch ! :)
